name: Zip Upload to S3

description: 'Archive files, upload to S3

inputs:
  inputFiles:
    description: 'Files to archive (e.g., *.*)'
    required: true
  s3BucketName:
    description: 'Name of the S3 bucket'
    required: true
  zipFileName:
    description: 'Name of the Zip archive to be created'
    required: true
  s3ObjectKey:
    description: 'S3 object key for the uploaded Zip archive'
    required: true
  addDirectoryPath:
    description: 'Whether to include the directory path in the zipped archive'
    type: boolean
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Archive Python files
      shell: bash
      run: |
        if [[ "${{ inputs.addDirectoryPath }}" == "true" ]]; then
          zip -r ${{ github.workspace }}/${{ inputs.zipFileName }} ${{ inputs.inputFiles }}
        else
          zip -jr ${{ github.workspace }}/${{ inputs.zipFileName }} ${{ inputs.inputFiles }}
        fi

    - name: Upload zip to S3
      shell: bash
      run: aws s3 cp ${{ github.workspace }}/${{ inputs.zipFileName }} s3://${{ inputs.s3BucketName }}/${{ inputs.s3ObjectKey }}
